//THIS FILE IS AUTOGENERATED BY Metadata\events\userEvent.json
using System;
using BKKWebApp.Data.Base;

namespace BKKWebApp.Data.Commands
{
    public class AddFavorite : Command
    {
		public string UserId { get; }
		public string Favorite { get; }

        public AddFavorite(string userId, string favorite)
        {
			UserId = userId;
			Favorite = favorite;
        }
    }
}
