//THIS FILE IS AUTOGENERATED BY Metadata\events\userEvent.json
using System;
using BKKWebApp.Data.Base;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BKKWebApp.Data.Events
{
    public class FavoriteAddedEvent : Event
    {
        public const string eventName = "favoriteAdded";

		public string UserId { get; set; }
		public string Favorite { get; set; }

        internal FavoriteAddedEvent(string source) : base(eventName)
        {
            var sourceObj = JObject.Parse(source);
            throw new NotImplementedException();
        }

        public FavoriteAddedEvent(Guid aggregateId, int version, string userId, string favorite) : base(aggregateId, version, eventName)
        {
			UserId = userId;
			Favorite = favorite;
        }

        public override string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
